### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by Auuki** [World-of-Tomorrow/NoItem#106]
20:42:02 [SEVERE] Could not pass event InventoryClickEvent to NoItem v3.0.7-SNAPSHOT org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427) at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477) at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462) at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:1364) at net.minecraft.server.v1_6_R2.Packet102WindowClick.handle(SourceFile:31) at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296) at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116) at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37) at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30) at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590) at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226) at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486) at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419) at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582) Caused by: java.lang.NullPointerException at net.worldoftomorrow.noitem.events.Handlers.handleNoWearInvClick(Handlers.java:406) at net.worldoftomorrow.noitem.events.Listeners.onInventoryClick(Listeners.java:67) at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:601) at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425) ... 14 more

Error showed after my friend died/opened inventory after death/opened workbench after death/collected his loot - one of these if this will help. However we repeated the situation and error didn't show again. This was on test server with CB 1.6.2 1.0, PEX, ExpSkills(BuySkills), WE, WG and some economy plugin installed. I haven't seen any problems caused by this error.

**Comment by konradmm** [comment]
Same problem for me (using Cauldron 1.6.4 - new mcpc+) and NoItem 3.1.0.
If there is no way to fix this, maybe just something to switch that off?
After 1 day of server, server.log is 300 mb...
