### ISSUE TITLE
onInventoryClick event bug

### ISSUE THREAD

**Issue by ghost** [World-of-Tomorrow/NoItem#111]
Hello, on my server I have the cook prohibited. However, it can all and each appears this error when someone does something in the furnace.

org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:437)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:31)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
    at net.minecraft.network.NetServerHandler.func_72523_a(NetServerHandler.java:2088)
    at net.minecraft.network.packet.Packet102WindowClick.func_73279_a(Packet102WindowClick.java:46)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R1/inventory/CraftItemStack
    at net.worldoftomorrow.noitem.events.Handlers.isCookable(Handlers.java:582)
    at net.worldoftomorrow.noitem.events.Handlers.handleNoCookInvClick(Handlers.java:450)
    at net.worldoftomorrow.noitem.events.Listeners.onInventoryClick(Listeners.java:69)
    at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:435)
    ... 15 more

**Comment by just-push-it** [comment]
I see the problem, but what version of NoItem and Bukkit are you using

**Comment by ghost** [comment]
i using mcpc+ 1.6.4 the latest version, und noitem 3.1.0
