### ISSUE TITLE
Could not pass event InventoryClickEvent to NoItem v3.1.0

### ISSUE THREAD

**Issue by JohOply** [World-of-Tomorrow/NoItem#114]
Hi, i have this error

I use Spigot 1.7.10-R0.2-b1656 and NoItem release 3.1.0

I have this error[21:13:00 ERROR]: Could not pass event InventoryClickEvent to NoItem v3.1.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1477) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R1/inventory/CraftItemStack
at net.worldoftomorrow.noitem.events.Handlers.isCookable(Handlers.java:582) ~[?:?]
at net.worldoftomorrow.noitem.events.Handlers.handleNoCookInvClick(Handlers.java:460) ~[?:?]
at net.worldoftomorrow.noitem.events.Listeners.onInventoryClick(Listeners.java:69) ~[?:?]
at sun.reflect.GeneratedMethodAccessor314.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-1.7.10-R0.2-1656.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
... 13 more

**Comment by selectj** [comment]
I've got this too
