### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when using Project Tables

### ISSUE THREAD

**Issue by nvx** [World-of-Tomorrow/NoItem#41]
Not 100% reproducible, but I had just restarted my server, see issue #40 for configs/versions/debug as nothing has changed since then to save repeating myself, and one of my players logged in, then started crafting Tin Ore out of Industrial Craft 2's UU Matter. It seems whenever he does, the following spam occurs in the console.

Not all crafting has caused this issue, but I have spotted it once before, but didn't think much of it. NoItem version is still 2.0.7-SNAPSHOT-193.

2012-10-04 02:19:41 [SEVERE] java.lang.ArrayIndexOutOfBoundsException: 9
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.InventoryCrafting.setItem(InventoryCrafting.java:124)
2012-10-04 02:19:41 [SEVERE]    at net.worldoftomorrow.nala.ni.listeners.EventListener.onInventoryClick(EventListener.java:331)
2012-10-04 02:19:41 [SEVERE]    at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
2012-10-04 02:19:41 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-10-04 02:19:41 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2012-10-04 02:19:41 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
2012-10-04 02:19:41 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2012-10-04 02:19:41 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
2012-10-04 02:19:41 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1082)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.Packet102WindowClick.handle(SourceFile:28)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:251)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:106)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:82)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:569)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2012-10-04 02:19:41 [SEVERE] java.lang.ArrayIndexOutOfBoundsException: 9
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.InventoryCrafting.setItem(InventoryCrafting.java:124)
2012-10-04 02:19:41 [SEVERE]    at net.worldoftomorrow.nala.ni.listeners.EventListener.onInventoryClick(EventListener.java:331)
2012-10-04 02:19:41 [SEVERE]    at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
2012-10-04 02:19:41 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-10-04 02:19:41 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2012-10-04 02:19:41 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
2012-10-04 02:19:41 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2012-10-04 02:19:41 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
2012-10-04 02:19:41 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1082)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.Packet102WindowClick.handle(SourceFile:28)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:251)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:106)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:82)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:569)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
2012-10-04 02:19:41 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by nvx** [comment]
I should note that no UU-Matter related recipes, nor recipes using tin ore, are restricted at the moment with NoItem or anything else.

I've further found out that he's using space click to make stacks at once (rather than one by one) in case that helps you to reproduce the issue.

**Comment by just-push-it** [comment]
Yeah, I also encountered this error in my testing when trying to reproduce bug #40 and I am already working on the issue :) Thanks for your continued input!
