### ISSUE TITLE
[SEVERE] Could not pass event BrewEvent to NoItem

### ISSUE THREAD

**Issue by clucky** [World-of-Tomorrow/NoItem#6]
18:05:08 [SEVERE] Could not pass event BrewEvent to NoItem
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
    at net.minecraft.server.TileEntityBrewingStand.p(TileEntityBrewingStand.java:132)
    at net.minecraft.server.TileEntityBrewingStand.q_(TileEntityBrewingStand.java:61)
    at net.minecraft.server.World.tickEntities(World.java:1177)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:558)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:571)
    at java.util.ArrayList.get(ArrayList.java:349)
    at net.worldoftomorrow.nala.ni.BrewingListener.onPotionBrew(BrewingListener.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
    ... 8 more

[INFO] This server is running CraftBukkit version git-Bukkit-1.2.5-R4.0-b2222jnks (MC: 1.2.5) (Implementing API version 1.2.5-R4.0)

I'm assuming this is from brewing being I've never seen it before since yesterday when the first player on my server got a blaze rod (took 1 month and 5 days for the first player to get a blaze rod, lol)

**Comment by clucky** [comment]
Fixed this one by updating rofl
