### ISSUE TITLE
[SEVERE] Error occurred while enabling NoItem v2.0.3 (Is it up to date?)

### ISSUE THREAD

**Issue by clucky** [World-of-Tomorrow/NoItem#7]
18:38:40 [SEVERE] Error occurred while enabling NoItem v2.0.3 (Is it up to date?)
java.lang.NullPointerException
    at net.worldoftomorrow.nala.ni.Updater.<init>(Updater.java:30)
    at net.worldoftomorrow.nala.ni.NoItem.onEnable(NoItem.java:19)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:256)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:238)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:381)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:368)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:197)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:432)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

[INFO] This server is running CraftBukkit version git-Bukkit-1.2.5-R4.0-b2222jnks (MC: 1.2.5) (Implementing API version 1.2.5-R4.0)

I just updated to the newest version of NoItem and got this error.

**Comment by clucky** [comment]
Also seems to not be working with R3.0 either for me. Going to try deleting config

**Comment by clucky** [comment]
That fixed it.

**Comment by just-push-it** [comment]
Would that mean that your last report is now fixed?

**Comment by just-push-it** [comment]
And then 2.0.4 is the latest version, the stack trace says its 2.0.3 so..

**Comment by clucky** [comment]
I just deleted the config, it fixed the problem. I am updating from like 1.6 xD I think my config became majorly outdated
